server:
  port: 8080

spring:
  application:
    name: zuul-gateway
  #DB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_notification
    username:
    password:
    #initialization-mode: always

zuul:
  routes:
    client-hello:
      url: http://localhost:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
